AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Self-Healing Infrastructure: EKS Cluster'

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: SelfHealingEKSCluster
      Version: '1.21'
      RoleArn: arn:aws:iam::123456789012:role/EKS-Cluster-Role
      ResourcesVpcConfig:
        SubnetIds: [ "subnet-12345abcde", "subnet-67890fghij" ]
Outputs:
  ClusterName:
    Description: The name of the EKS cluster
    Value: !Ref EKSCluster
