default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: your_username
  password: your_password
  host: localhost

development:
  <<: *default
  database: users_microservice_development

test:
  <<: *default
  database: users_microservice_test

production:
  <<: *default
  database: users_microservice_production
  username: users_microservice
  password: <%= ENV['USERS_MICROSERVICE_DATABASE_PASSWORD'] %>
