version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.0
      nodejs: 14
    commands:
      - echo Installing Ruby and Node.js dependencies...
      - gem install bundler
      - bundle install
      - npm install --global yarn
      - yarn install
  
  pre_build:
    commands:
      - echo Preparing the database...
      - RAILS_ENV=test bundle exec rake db:create db:schema:load
      
  build:
    commands:
      - echo Running tests...
      - bundle exec rspec
      - echo Building the Docker image...
      - docker build -t aws-self-healing/users:$CODEBUILD_RESOLVED_SOURCE_VERSION .
  
  post_build:
    commands:
      - echo Pushing the Docker image...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker push aws-self-healing/users:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Writing image definitions file...
      - printf '[{"name":"users-service","imageUri":"aws-self-healing/users:%s"}]' $CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
